export { AREAS, BATTLE_SPACE, LINES } from './board.js'
export type { Area, Line, Square, SquareIndex } from './board.js'
export { ORIENTATIONS } from './orientation.js'
export type { Orientation } from './orientation.js'
export { RELATIONS_FROM_PLAYER, RELATIONS_FROM_UNIT } from './relation.js'
export type { RelationFromPlayer, RelationFromUnit } from './relation.js'
export { PLAYER_ZONES, SHARED_ZONES, ZONES } from './zone.js'
export type { PlayerZone, SharedZone, Zone } from './zone.js'
